// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	bun "github.com/uptrace/bun"
)

// Worker is an autogenerated mock type for the Worker type
type Worker struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *Worker) Get() *bun.DB {
	ret := _m.Called()

	var r0 *bun.DB
	if rf, ok := ret.Get(0).(func() *bun.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bun.DB)
		}
	}

	return r0
}

// Init provides a mock function with given fields: _a0
func (_m *Worker) Init(_a0 *bun.DB) {
	_m.Called(_a0)
}
